"""Os textos da planilha: o que cada linha é e como foi calculada, em linguagem simples.

Ficam separados do desenho das abas para poderem ser revisados como texto. A
chave de `LINHAS` é o nome interno da linha, o mesmo usado em `planilha.py`.
"""

# Uma frase por linha, mostrada ao lado dos números.
LINHAS: dict[str, str] = {
    # --- demonstrativos
    "receita": "Tudo o que a empresa vendeu no período, já sem impostos sobre a venda.",
    "custo": "O que custou produzir o que foi vendido, incluindo a depreciação das fábricas e minas.",
    "lucro_bruto": "Receita menos custo dos produtos. O que sobra antes das despesas da empresa.",
    "despesas_vendas": "Gastos para vender e entregar: frete, comissões, equipe comercial.",
    "despesas_ga": "Gastos da administração: salários do escritório, sistemas, serviços.",
    "perdas_recuperabilidade": "Baixa contábil de um ativo que passou a valer menos (impairment). Não sai do caixa.",
    "despesas_operacionais": "Soma de todas as despesas e receitas operacionais abaixo do lucro bruto.",
    "equivalencia": "Parte do lucro de empresas das quais ela é sócia sem controlar. Não entra no caixa.",
    "ebit": "Lucro da operação, antes de juros e imposto de renda. Lucro bruto menos despesas.",
    "resultado_financeiro": "Juros recebidos menos juros pagos, mais variação cambial e derivativos.",
    "lair": "Lucro antes do imposto de renda: EBIT mais o resultado financeiro.",
    "ir": "Imposto de renda e contribuição social sobre o lucro.",
    "lucro_liquido": "O que sobra para os sócios depois de tudo: custos, despesas, juros e impostos.",
    "lucro_controladores": "A parte do lucro que pertence aos acionistas da empresa, sem os sócios de controladas.",
    "da": "Desgaste contábil de máquinas, minas e prédios no período. É custo, mas não sai do caixa.",
    "fco": "Dinheiro que a operação gerou de verdade no período, depois de impostos e capital de giro.",
    "capex": "Dinheiro investido em máquinas, minas, fábricas e sistemas.",
    "dividendos_pagos": "Dinheiro entregue aos acionistas como dividendos e juros sobre capital próprio.",
    "caixa": "Dinheiro em conta e aplicações de resgate imediato.",
    "aplicacoes": "Aplicações financeiras de curto prazo.",
    "contas_receber": "Vendas já feitas que os clientes ainda não pagaram.",
    "estoques": "Matéria-prima e produto pronto que ainda não foi vendido.",
    "ativo_circulante": "Tudo o que vira dinheiro em até um ano.",
    "investimentos": "Participação em outras empresas, pelo valor registrado no balanço.",
    "imobilizado": "Máquinas, minas, fábricas e terrenos, já descontada a depreciação.",
    "intangivel": "Direitos, licenças, softwares e ágio de aquisições.",
    "ativo_total": "Tudo o que a empresa tem.",
    "fornecedores": "Compras já recebidas que a empresa ainda não pagou.",
    "divida_cp": "Empréstimos e financiamentos que vencem em até um ano.",
    "passivo_circulante": "Tudo o que a empresa tem de pagar em até um ano.",
    "divida_lp": "Empréstimos e financiamentos que vencem depois de um ano.",
    "patrimonio_liquido": "O que é dos sócios: ativo total menos todas as dívidas e obrigações.",
    "minoritarios": "A parte do patrimônio que pertence a sócios de empresas controladas.",
    # --- indicadores
    "ebitda": "EBIT + depreciação. Aproxima o caixa que a operação gera antes de investir e pagar juros.",
    "ebitda_recorrente": "EBITDA sem as perdas por recuperabilidade, que não se repetem. É a base da projeção.",
    "margem_ebitda_recorrente": "EBITDA sem perdas por recuperabilidade dividido pela receita.",
    "custo_caixa": "Custo dos produtos sem a depreciação: o custo que de fato sai do caixa.",
    "outras_operacionais": "Despesas operacionais que não são vendas nem administrativas: provisões, baixas, ganhos avulsos.",
    "nopat": "Lucro da operação depois do imposto, como se a empresa não tivesse dívida. (EBIT − equivalência) × (1 − 34%).",
    "crescimento_receita": "Receita do período dividida pela do período anterior, menos 1.",
    "margem_bruta": "Lucro bruto dividido pela receita: quanto sobra de cada real vendido depois do custo.",
    "margem_ebitda": "EBITDA dividido pela receita: quanto de cada real vendido vira caixa operacional.",
    "margem_ebit": "EBIT dividido pela receita.",
    "margem_liquida": "Lucro líquido dividido pela receita: quanto de cada real vendido sobra para o sócio.",
    "outras_pct": "Outras receitas e despesas operacionais divididas pela receita.",
    "capex_pct": "Capex dividido pela receita: quanto da venda é reinvestido.",
    "ativo_fixo": "Imobilizado + intangível: os bens que a empresa usa para produzir.",
    "da_pct_ativo_fixo": "Depreciação do ano dividida pelo ativo fixo do ano anterior: a velocidade do desgaste.",
    "aliquota_efetiva": "Imposto de renda dividido pelo lucro antes do imposto: o que a empresa pagou de fato.",
    "prazo_recebimento": "Contas a receber ÷ receita × 365: quantos dias o cliente demora para pagar.",
    "prazo_estoque": "Estoques ÷ custo caixa × 365: quantos dias o produto fica parado.",
    "prazo_pagamento": "Fornecedores ÷ custo caixa × 365: quantos dias a empresa demora para pagar.",
    "ciclo_caixa": "Prazo de recebimento + prazo de estoque − prazo de pagamento: dias que a empresa financia do próprio bolso.",
    "capital_de_giro": "Contas a receber + estoques − fornecedores: dinheiro preso no dia a dia da operação.",
    "caixa_total": "Caixa + aplicações financeiras.",
    "divida_bruta": "Empréstimos de curto prazo + empréstimos de longo prazo.",
    "divida_liquida": "Dívida bruta − caixa: o que a empresa deve depois de usar todo o dinheiro que tem.",
    "divida_liquida_ebitda": "Dívida líquida ÷ EBITDA: quantos anos de geração de caixa pagam a dívida. Acima de 3x é alto.",
    "liquidez_corrente": "Ativo circulante ÷ passivo circulante: acima de 1, o curto prazo está coberto.",
    "roe": "Lucro dos controladores ÷ patrimônio dos controladores: o retorno do dinheiro do sócio.",
    "roic": "NOPAT ÷ (capital de giro + ativo fixo): o retorno de todo o capital posto na operação.",
    "fcl_simples": "Caixa das operações − capex: o que sobra depois de investir.",
    # --- projeção
    "p_crescimento": "2026 repete os últimos doze meses. De 2027 em diante vale o crescimento escolhido no Painel.",
    "p_margem": "Sai da margem dos últimos doze meses em 2026 e chega, em linha reta, à margem escolhida no Painel em 2030.",
    "p_receita": "Receita do ano anterior × (1 + crescimento).",
    "p_custo_caixa": "O que sobra para a margem fechar: receita − despesas + equivalência − EBITDA.",
    "p_despesas": "Receita × percentual de despesas operacionais (aba Premissas).",
    "p_equivalencia": "Valor fixo da aba Premissas.",
    "p_ebitda": "Receita × margem EBITDA do cenário.",
    "p_da": "Ativo fixo do início do ano × taxa de depreciação (aba Premissas).",
    "p_ebit": "EBITDA − depreciação.",
    "p_receita_financeira": "Caixa do início do ano × rendimento do caixa.",
    "p_despesa_financeira": "Dívida do início do ano × juros pagos sobre a dívida (aba Premissas).",
    "p_resultado_financeiro": "Rendimento do caixa − juros da dívida.",
    "p_lair": "EBIT + resultado financeiro.",
    "p_ir": "(Lucro antes do imposto − equivalência) × alíquota. Sem lucro, não há imposto.",
    "p_lucro_liquido": "Lucro antes do imposto − imposto.",
    "p_capex": "Receita × percentual de capex (aba Premissas).",
    "p_ativo_fixo": "Ativo fixo anterior + capex − depreciação.",
    "p_contas_receber": "Receita × prazo de recebimento ÷ 365.",
    "p_estoques": "Custo dos produtos × prazo de estoque ÷ 365.",
    "p_fornecedores": "Custo dos produtos × prazo de pagamento ÷ 365.",
    "p_capital_de_giro": "Contas a receber + estoques − fornecedores.",
    "p_variacao_giro": "Capital de giro do ano − o do ano anterior. Positivo consome caixa.",
    "p_dividendos": "Lucro líquido × percentual distribuído (aba Premissas). Sem lucro, não há dividendo.",
    "p_variacao_caixa": "FCFE − dividendos: o que entra ou sai do caixa no ano.",
    "p_caixa_total": "Caixa anterior + variação do caixa. É a conta que fecha o balanço.",
    "p_investimentos": "Saldo anterior + equivalência do ano.",
    "p_outros_ativos": "Tudo o que o modelo não projeta linha a linha; fica constante.",
    "p_ativo_total": "Soma de todas as linhas do ativo.",
    "p_divida_bruta": "Dívida anterior + captação líquida (aba Premissas).",
    "p_outros_passivos": "Tudo o que o modelo não projeta linha a linha; fica constante.",
    "p_patrimonio_liquido": "Patrimônio anterior + lucro líquido − dividendos.",
    "p_passivo_e_pl": "Fornecedores + dívida + outros passivos + patrimônio líquido.",
    "p_checagem_balanco": "Ativo − (passivo + patrimônio). Se não der zero, há erro no modelo.",
    "p_margem_ebit": "EBIT ÷ receita.",
    "p_divida_liquida": "Dívida bruta − caixa.",
    "p_divida_liquida_ebitda": "Dívida líquida ÷ EBITDA.",
    "p_roic": "NOPAT ÷ (capital de giro + ativo fixo do início do ano).",
    # --- FCFF e FCFE
    "f_ebit": "Lucro da operação antes de juros e impostos (aba Projeção).",
    "f_equivalencia": "Sai da conta: é lucro de outras empresas, não entra no caixa desta.",
    "f_imposto": "(EBIT − equivalência) × alíquota: o imposto que a operação pagaria sem dívida.",
    "f_nopat": "EBIT − equivalência − imposto: o lucro da operação depois do imposto.",
    "f_da": "Volta para a conta: foi descontada no EBIT, mas não saiu do caixa.",
    "f_capex": "Sai da conta: dinheiro investido em ativos.",
    "f_variacao_giro": "Sai da conta: dinheiro a mais preso em clientes e estoques.",
    "f_fcff": "NOPAT + depreciação − capex − variação do giro. É o caixa livre para credores e acionistas.",
    "f_lucro_liquido": "Lucro depois de juros e impostos (aba Projeção).",
    "f_captacao": "Dívida nova menos dívida paga no ano.",
    "f_fcfe": "Lucro líquido − equivalência + depreciação − capex − variação do giro + captação. É o caixa livre só do acionista.",
    "f_capex_terminal": "Depois de 2030 a empresa só repõe o que desgasta: depreciação × múltiplo da aba Premissas.",
    "f_fcff_terminal": "FCFF de 2030 com o capex de reposição no lugar do capex do ano.",
    "f_fcfe_terminal": "FCFE de 2030 com o capex de reposição no lugar do capex do ano.",
    # --- WACC
    "w_rf": "O juro de um investimento sem risco de calote: o título do Tesouro prefixado de dez anos.",
    "w_beta": "Quanto a ação costuma andar quando a bolsa anda 1%. Acima de 1, oscila mais que o mercado.",
    "w_premio": "O retorno a mais que o investidor exige para estar em ações em vez de títulos do governo.",
    "w_adicional": "Prêmio extra por risco próprio da empresa. Zero nesta versão.",
    "w_ke": "Ke = juro sem risco + beta × prêmio de mercado + prêmio adicional. É o retorno que o acionista exige.",
    "w_kd": "O que a dívida custa à empresa, em reais. Vem do custo que ela divulga (aba Premissas).",
    "w_ir": "Alíquota de imposto sobre o lucro.",
    "w_kd_liquido": "Kd × (1 − alíquota). O juro reduz o imposto a pagar, então a dívida custa menos.",
    "w_wd": "Quanto do capital da empresa vem de dívida.",
    "w_we": "1 − peso da dívida: quanto do capital vem dos sócios.",
    "w_wacc": "Ke × peso dos sócios + Kd após imposto × peso da dívida. É o custo médio do capital.",
    "w_ajuste": "WACC em uso − WACC do CAPM: quanto o cenário ou o ajuste manual deslocou a taxa.",
    "w_wacc_uso": "A taxa escolhida no Painel. É ela que desconta o FCFF.",
    "w_ke_uso": "Ke + o mesmo ajuste. É a taxa que desconta o FCFE.",
    "w_mercado": "Preço da ação × número de ações.",
    "w_divida": "Dívida bruta no último balanço.",
    "w_wd_mercado": "Dívida ÷ (dívida + valor de mercado): serve para conferir o peso usado.",
    # --- valor justo
    "v_fcff": "O caixa livre de cada ano (aba FCFF).",
    "v_fracao": "De 2026 só conta a parte do ano que vem depois do último balanço. Os outros anos contam inteiros.",
    "v_fim": "Quantos anos faltam, a partir do último balanço, até o fim de cada ano.",
    "v_meio": "O caixa entra ao longo do ano, não no último dia: usa-se o meio do período.",
    "v_fator": "1 ÷ (1 + WACC) elevado ao número de anos. Quanto vale hoje R$ 1 recebido naquela data.",
    "v_vp": "FCFF × parte do ano × fator de desconto.",
    "v_wacc": "A taxa de desconto em uso (aba WACC).",
    "v_g": "A taxa à qual o caixa cresce para sempre depois de 2030 (aba Premissas).",
    "v_fcff_terminal": "O FCFF de 2030 ajustado para repetir para sempre (aba FCFF).",
    "v_vt": "FCFF normalizado × (1 + g) ÷ (WACC − g). Resume em um número todos os anos depois de 2030.",
    "v_vp_vt": "Valor terminal ÷ (1 + WACC) elevado aos anos até o fim de 2030.",
    "v_soma_vp": "Soma dos valores presentes de 2026 a 2030.",
    "v_ev": "Valor presente dos fluxos + valor presente do valor terminal. Quanto vale a operação inteira.",
    "v_divida_liquida": "Sai: é dos credores (dívida bruta − caixa, no último balanço).",
    "v_minoritarios": "Sai: é dos sócios das controladas.",
    "v_investimentos": "Entra: participações em outras empresas, que o FCFF não contou.",
    "v_outros": "Sai: outros passivos que funcionam como dívida (aba Premissas).",
    "v_equity": "EV − dívida líquida − minoritários + investimentos − outros. Quanto vale a parte dos acionistas.",
    "v_acoes": "Número de ações em circulação, sem as que estão na tesouraria.",
    "v_preco_justo": "Valor do acionista ÷ número de ações.",
    "v_preco": "Último fechamento na B3.",
    "v_potencial": "Preço justo ÷ preço de mercado − 1.",
    "v_peso_vt": "Quanto do valor da empresa vem de depois de 2030. Quanto maior, mais o resultado depende do longo prazo.",
    "v_ev_ebitda": "Valor da empresa ÷ EBITDA de 2026: o múltiplo que o DCF está pagando.",
    "v_fcfe": "O caixa livre do acionista de cada ano (aba FCFF).",
    "v_fator_ke": "1 ÷ (1 + Ke) elevado ao número de anos.",
    "v_vp_fcfe": "FCFE × parte do ano × fator de desconto.",
    "v_ke": "A taxa que desconta o caixa do acionista (aba WACC).",
    "v_fcfe_terminal": "O FCFE de 2030 ajustado para repetir para sempre (aba FCFF).",
    "v_vp_vt_fcfe": "Valor terminal do FCFE trazido a valor de hoje pelo Ke.",
    "v_equity_fcfe": "Soma dos FCFE descontados, menos minoritários, mais investimentos. Deve ficar perto do valor pelo FCFF.",
    "v_preco_fcfe": "Valor do acionista pelo FCFE ÷ número de ações.",
    # --- caixa
    "c_operacao": "EBITDA sem equivalência: o caixa que a operação produz.",
    "c_rendimento": "Juros recebidos sobre o caixa aplicado.",
    "c_captacao": "Dívida nova que entrou, se a captação líquida foi positiva.",
    "c_entradas": "Soma das entradas.",
    "c_impostos": "Imposto de renda e contribuição social.",
    "c_capex": "Investimento em ativos.",
    "c_giro": "Dinheiro a mais preso em clientes e estoques.",
    "c_juros": "Juros pagos sobre a dívida.",
    "c_amortizacao": "Dívida paga, se a captação líquida foi negativa.",
    "c_dividendos": "Dinheiro entregue aos acionistas.",
    "c_saidas": "Soma das saídas.",
    "c_variacao": "Entradas − saídas: o que o caixa cresceu ou encolheu no ano.",
    "c_caixa_final": "Saldo de caixa no fim do ano (aba Projeção).",
    "c_confere": "Tem de ser zero: a conta daqui bate com a da projeção.",
}

# Termo, o que é, como se calcula, em que aba ver.
GLOSSARIO: tuple[tuple[str, str, str, str], ...] = (
    (
        "Receita líquida",
        "Tudo o que a empresa vendeu, sem os impostos sobre a venda.",
        "Vem direto da DRE.",
        "Demonstrativos",
    ),
    (
        "EBIT",
        "Lucro da operação, antes de juros e imposto de renda.",
        "Lucro bruto − despesas operacionais.",
        "Demonstrativos",
    ),
    (
        "EBITDA",
        "Aproximação do caixa que a operação gera antes de investir e pagar juros.",
        "EBIT + depreciação e amortização.",
        "Demonstrativos",
    ),
    (
        "Margem EBITDA",
        "Quanto de cada real vendido vira caixa operacional.",
        "EBITDA ÷ receita.",
        "Demonstrativos",
    ),
    (
        "Depreciação e amortização",
        "Desgaste contábil dos ativos. É custo, mas não sai do caixa.",
        "Taxa × ativo fixo do início do ano.",
        "Projeção",
    ),
    (
        "NOPAT",
        "Lucro da operação depois do imposto, como se não houvesse dívida.",
        "(EBIT − equivalência) × (1 − alíquota).",
        "FCFF",
    ),
    (
        "Capex",
        "Dinheiro investido em máquinas, minas e fábricas.",
        "Percentual da receita.",
        "Projeção",
    ),
    (
        "Opex",
        "Despesas para a empresa funcionar: vendas, administração e outras.",
        "Percentual da receita.",
        "Projeção",
    ),
    (
        "Capital de giro",
        "Dinheiro preso no dia a dia: o que os clientes devem e o estoque, menos o que se deve a fornecedores.",
        "Contas a receber + estoques − fornecedores.",
        "Projeção",
    ),
    (
        "Ciclo de caixa",
        "Quantos dias a empresa financia a operação do próprio bolso.",
        "Prazo de recebimento + prazo de estoque − prazo de pagamento.",
        "Demonstrativos",
    ),
    (
        "FCFF",
        "Caixa livre da empresa: o que sobra para credores e acionistas depois de investir.",
        "NOPAT + depreciação − capex − variação do capital de giro.",
        "FCFF",
    ),
    (
        "FCFE",
        "Caixa livre do acionista: o que sobra depois de pagar juros e dívida.",
        "Lucro líquido − equivalência + depreciação − capex − variação do giro + captação.",
        "FCFF",
    ),
    (
        "Juro sem risco (Rf)",
        "O retorno de um investimento sem risco de calote.",
        "Taxa do Tesouro prefixado de dez anos.",
        "WACC",
    ),
    (
        "Beta",
        "Quanto a ação anda quando a bolsa anda 1%.",
        "Inclinação da regressão dos retornos da ação contra os do BOVA11.",
        "WACC",
    ),
    (
        "Prêmio de risco de mercado",
        "Retorno a mais exigido para investir em ações.",
        "Estimativa de Damodaran (NYU).",
        "WACC",
    ),
    (
        "CAPM / Ke",
        "O retorno que o acionista exige para investir na empresa.",
        "Rf + beta × prêmio de mercado.",
        "WACC",
    ),
    (
        "Kd",
        "O juro que a empresa paga pela dívida.",
        "Depois do imposto: Kd × (1 − alíquota).",
        "WACC",
    ),
    (
        "WACC",
        "Custo médio do capital da empresa. É a taxa que desconta o FCFF.",
        "Ke × peso dos sócios + Kd após imposto × peso da dívida.",
        "WACC",
    ),
    (
        "Valor presente",
        "Quanto vale hoje um dinheiro que só chega no futuro.",
        "Fluxo ÷ (1 + WACC) elevado ao número de anos.",
        "Valor justo",
    ),
    (
        "Perpetuidade / valor terminal",
        "O valor de todos os anos depois do último projetado.",
        "FCFF × (1 + g) ÷ (WACC − g).",
        "Valor justo",
    ),
    (
        "g",
        "Taxa à qual o caixa cresce para sempre depois de 2030.",
        "Inflação esperada de longo prazo: crescimento real zero.",
        "Premissas",
    ),
    (
        "Enterprise Value (EV)",
        "Valor da operação inteira, para credores e acionistas.",
        "Soma dos FCFF descontados + valor terminal descontado.",
        "Valor justo",
    ),
    (
        "Dívida líquida",
        "O que a empresa deve depois de usar todo o caixa.",
        "Dívida bruta − caixa e aplicações.",
        "Demonstrativos",
    ),
    (
        "Equity Value",
        "Valor da parte dos acionistas.",
        "EV − dívida líquida − minoritários + investimentos.",
        "Valor justo",
    ),
    (
        "Preço justo",
        "Quanto vale cada ação segundo o modelo.",
        "Equity Value ÷ número de ações.",
        "Valor justo",
    ),
    (
        "EV/EBITDA",
        "Quantos anos de EBITDA o mercado paga pela empresa.",
        "(Valor de mercado + dívida líquida + minoritários) ÷ EBITDA.",
        "Múltiplos",
    ),
    (
        "P/L",
        "Quantos anos de lucro o mercado paga pela ação.",
        "Valor de mercado ÷ lucro líquido.",
        "Múltiplos",
    ),
    (
        "P/VP",
        "Quanto o mercado paga por cada real de patrimônio.",
        "Valor de mercado ÷ patrimônio líquido.",
        "Múltiplos",
    ),
    (
        "ROIC",
        "Retorno de todo o capital posto na operação.",
        "NOPAT ÷ (capital de giro + ativo fixo).",
        "Demonstrativos",
    ),
    (
        "ROE",
        "Retorno do dinheiro do acionista.",
        "Lucro líquido ÷ patrimônio líquido.",
        "Demonstrativos",
    ),
    (
        "Dívida líquida / EBITDA",
        "Quantos anos de geração de caixa pagam a dívida.",
        "Dívida líquida ÷ EBITDA.",
        "Demonstrativos",
    ),
    (
        "Sensibilidade",
        "Quanto o preço justo muda quando uma premissa muda.",
        "O valuation refeito para cada par de WACC e g.",
        "Valor justo",
    ),
    (
        "Correlação",
        "Mede se duas coisas andam juntas: 1 é sempre juntas, 0 é sem relação, −1 é sempre opostas.",
        "Entre a variação mensal da ação e a do minério.",
        "Correlação",
    ),
    (
        "R²",
        "Quanto da oscilação da ação o minério explica.",
        "Correlação elevada ao quadrado.",
        "Correlação",
    ),
)

# Passo a passo do valor justo: título e explicação de cada etapa.
PASSOS: tuple[tuple[str, str], ...] = (
    (
        "1. Quanto caixa a empresa gera: o FCFF",
        "Tudo começa pelo caixa livre da empresa. Pega-se o lucro da operação depois do imposto "
        "(NOPAT), soma-se a depreciação, que é custo mas não sai do caixa, e tira-se o que foi "
        "investido em ativos (capex) e em capital de giro.",
    ),
    (
        "2. Quanto custa o dinheiro: o WACC",
        "Um real daqui a cinco anos vale menos que um real hoje. A taxa que faz essa conta é o "
        "WACC: a média entre o retorno que o acionista exige (Ke, pelo CAPM) e o juro da dívida "
        "depois do imposto.",
    ),
    (
        "3. Trazer cada fluxo a valor de hoje",
        "Cada FCFF projetado é dividido por (1 + WACC) elevado ao número de anos até ele chegar. "
        "De 2026 só entra a parte do ano que ainda não aconteceu.",
    ),
    (
        "4. O que vem depois de 2030: a perpetuidade",
        "A empresa não acaba em 2030. Supõe-se que o caixa cresce para sempre a uma taxa g, igual "
        "à inflação. A fórmula de Gordon resume todos esses anos em um número, o valor terminal.",
    ),
    (
        "5. Valor da empresa (Enterprise Value)",
        "Somando os fluxos descontados e o valor terminal descontado chega-se ao valor da operação "
        "inteira, que pertence a credores e acionistas.",
    ),
    (
        "6. Do valor da empresa ao valor do acionista (Equity Value)",
        "Tira-se o que é dos credores (dívida líquida) e dos sócios das controladas (minoritários) "
        "e soma-se o que a empresa tem em participações.",
    ),
    (
        "7. Preço justo por ação",
        "O valor do acionista dividido pelo número de ações dá o preço justo, que se compara com "
        "o preço na bolsa.",
    ),
)
